### ISSUE TITLE
haskell.org DNS is misconfigured?

### ISSUE THREAD

**Issue by tomjaguarpaw** [haskell-infra/haskell-admins#5]
Users are reporting missing messages from haskell-cafe. Viktor Dukhovni diagnosed the problem as DNS misconfiguration. See <https://mail.haskell.org/pipermail/haskell-cafe/2021-November/134894.html>.

**Comment by gbaz** [comment]
We set up a new mail host (had to migrate an existing one) and gave it an elastic/floating IP so we can keep the IP reputation even when we have to move hosts again. However, turns out floating IPs don't have reversedns by default on our host, so we had to contact them to get this fixed. Should be resolved shortly.

**Comment by gbaz** [comment]
this was all resolved but somehow the new sender still had low rep so for now we've disabled using it -- this does need to get reenabled in the future. having only one sender with decent rep is a failure point for us.
